# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UiGang' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UiGang

pod 'Alamofire', '~> 5.7'

end
